### ISSUE TITLE
No data

### ISSUE THREAD

**Issue by catchlight** [clivebeckett/grav-plugin-admin-addon-media-metadata#13]
I've got this installed on Grav v1.6.26 with Admin v1.9.15 and the hover works fine for entering data, but nothing shows up in the code.

<img width="858" alt="CleanShot 2020-06-18 at 19 35 11" src="https://user-images.githubusercontent.com/1256376/85085597-f5cc2500-b19d-11ea-9038-607f04d1d20e.png">
<img width="548" alt="CleanShot 2020-06-18 at 19 57 11" src="https://user-images.githubusercontent.com/1256376/85085602-f795e880-b19d-11ea-8181-7e33eee29c81.png">

**Comment by clivebeckett** [comment]
Hi @catchlight,

thanks for trying my plugin and for getting in touch. I reckon the source code shows your public website? You still have to tell your templates to show the metadata – an example:
```twig
{% for img in page.media.images %}
    <a href="{{ img.url }}" data-lightbox="{{ page.folder }}" data-title="{{ img.meta.caption }}"><img src="{{ img.cropResize(800, 450).url }}" alt="{{ img.meta.alt }}" title="{{ img.meta.title }}"></a>
{% endfor %}
```
Anyway, this is independent of my plugin and has always been necessary. My plugin only provides a way to _write_ the [image].meta.yaml files from within the Admin Plugin. But you have always needed to tell your templates to output the data.

When it comes to embedding your image directly in a page’s markdown you just provide alt and title in the markdown. Example and more [explanation on Media in the Grav docs](https://learn.getgrav.org/16/content/media#html).

I hope that helped. If I understood anything wrong, let me know.

Cheers,
Clive.

**Comment by catchlight** [comment]
Ah! Sorry, I've been digging through my theme docs trying to figure it out for a few days. What you say makes sense. I will give it a try. Thanks so much.

**Comment by clivebeckett** [comment]
Hi @catchlight,
No probs :) Were you able to make it work? Or is there anything missing in the plugin?
Cheers,
Clive.

**Comment by catchlight** [comment]
Yes. I was able to find the relevant image placements in my theme and update the code accordingly. Works perfectly.

Thanks!
