### ISSUE TITLE
Don't understand Additional Page Specific Metadata Fields instructions

### ISSUE THREAD

**Issue by hughbris** [clivebeckett/grav-plugin-admin-addon-media-metadata#18]
In the README in the section "Additional Page Specific Metadata Fields (v1.1 and later)", it looks like something useful but I don't quite follow:

> You may also add page specific fields to a page’s frontmatter. _Note: The fields will be added to the form, not override the ones from the above mentioned config files:_

Could you please explain this another way or more fully so I can grok it? Where (page blueprints or individual pages) and why would I use this? I'm happy to suggest a clearer wording in a PR if it occurs to me.

Also, thank you for this invaluable plugin! :heart:  It should be integrated into Admin plugin IMHO.

**Comment by clivebeckett** [comment]
Hi Hugh!

Thank you for all your notes! They’re very much appreciated! Unfortunately I don’t have time for developing at the moment (and probably not in quite a while). I have moved my focus back to my other self who is a musician :)

As for this specific question … Is the following more understandable?

> *Note: The page specific fields will be added to those defined in the above mentioned config files. The page configuration will not override the plugin configuration.*

Or do you reckon this note can be dropped completely?

Thanks for your help!

Cheers,
Clive.

**Comment by bitstarr** [comment]
Late to the party, but since I'm doing maintenance: here the clarification, that I'm going to add to the readme:

> Having added this example code to the frontmatter of your page, it will add the new field 'Yet another field' to the metadata modal, but only for this specific page.
