### ISSUE TITLE
JS error with custom field names containing dots

### ISSUE THREAD

**Issue by hughbris** [clivebeckett/grav-plugin-admin-addon-media-metadata#20]
I added a couple of display fields with a dot in their name to my metadata modal and they prevented the form saving.

When I investigated in the browser console, there's this jQuery error: `Uncaught Error: Syntax error, unrecognized expression: [name=tip.alt]`.

If I was to guess the problem here, I'd say the dots needs to be escaped because they are being used as jQuery selectors.

This is easy enough to work around, but perhaps something to look at or at least a caution not to use field names with dots.

**Comment by bitstarr** [comment]
I'm sorry to say, but nesting/multi level arrays are not supported. I tired around to make it work but it would need too much logic and it's a bit of an edge case.
