### ISSUE TITLE
CORS Error when updating fields

### ISSUE THREAD

**Issue by rcheetah** [clivebeckett/grav-plugin-admin-addon-media-metadata#25]
When clicking on "save" in the modal filed, I get an endless loading state. The console contains errors due to CORS problems. The update file is loaded via http, not https.

```
admin-addon-media-rename.js?f14683cc7e:177 Mixed Content: The page at 'https://staging.feg-krems.at/de/admin/pages/aktivitaeten/kleingruppen/_gebetstreffen' was loaded over HTTPS, but requested an insecure resource 'http://staging.feg-krems.at/admin/update.json/task:AdminAddonMediaMetadataEdit'. This request has been blocked; the content must be served over HTTPS.
window.fetch @ admin-addon-media-rename.js?f14683cc7e:177
(anonymous) @ admin-addon-media-metadata.js?f14683cc7e:85
dispatch @ jquery-3.x.min.js?f14683cc7e:2
v.handle @ jquery-3.x.min.js?f14683cc7e:2
admin-addon-media-rename.js?f14683cc7e:177 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (admin-addon-media-rename.js?f14683cc7e:177:18)
    at HTMLButtonElement.<anonymous> (admin-addon-media-metadata.js?f14683cc7e:85:9)
    at HTMLDocument.dispatch (jquery-3.x.min.js?f14683cc7e:2:43090)
    at v.handle (jquery-3.x.min.js?f14683cc7e:2:41074)
```

```
admin-addon-media-rename.js?f14683cc7e:177 
       Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (admin-addon-media-rename.js?f14683cc7e:177:18)
    at HTMLButtonElement.<anonymous> (admin-addon-media-metadata.js?f14683cc7e:85:9)
    at HTMLDocument.dispatch (jquery-3.x.min.js?f14683cc7e:2:43090)
    at v.handle (jquery-3.x.min.js?f14683cc7e:2:41074)
window.fetch @ admin-addon-media-rename.js?f14683cc7e:177
(anonymous) @ admin-addon-media-metadata.js?f14683cc7e:85
dispatch @ jquery-3.x.min.js?f14683cc7e:2
v.handle @ jquery-3.x.min.js?f14683cc7e:2
Promise.then (async)
(anonymous) @ admin-addon-media-metadata.js?f14683cc7e:87
dispatch @ jquery-3.x.min.js?f14683cc7e:2
v.handle @ jquery-3.x.min.js?f14683cc7e:2
```

I tried to figure out, what went wrong. I found in the php file on line 177:

`'PATH' => $this->getAdminBase() . '/update.json/task:' . self::TASK_METADATA,`

Here the function ` $this->getAdminBase()` is used to get the root. I guess this should normally handle the protocol?!
I'm stuck. Is someone experiencing a similar error?

**Comment by bitstarr** [comment]
I cannot reproduce this situation. Using https, all my AJAX request are https too. The function you mentioned is calling `$this->grav['uri']->rootUrl(true)` which is getting the protocol and hostname directly from grav itself.

Did you set `system.custom_base_url` (system.yaml)? see https://github.com/getgrav/grav/blob/345086538caee1b4607a34b1d4429d08525e237e/system/src/Grav/Common/Uri.php#L168

**Comment by rcheetah** [comment]
Thank you for this tip! I will try that. At the moment I have troubles setting up environment config, as grav just crashes if I do so, but this is a different topic ^^
