### ISSUE TITLE
Limited functionality in Admin Plugin v1.10.0-rc.8

### ISSUE THREAD

**Issue by clivebeckett** [clivebeckett/grav-plugin-admin-addon-media-metadata#7]
The Admin Plugin v1.10.0 writes newly uploaded media files to a temporary folder first and moves them to the page folder only on saving the page. The `[mediafile].meta.yaml` will only be written for files already moved to the page folder, thus after the next page save.

Also I am not sure whether the event hook `onAdminAfterAddMedia` is still being fired. It seems like it isn’t.

I can solve the problem partly by removing the condition that checks whether the media file exists before writing the YAML file. But I’m not sure this is a good idea. And even then no empty `[mediafile].meta.yaml` will be created on upload (which is what happened before, triggered by the event hook `onAdminAfterAddMedia`.

**Comment by bitstarr** [comment]
I created a workaround for this by spying for the current folder name. #27
